package io.schiar.slowpoke

enum class Permission {
    BLUETOOTH,
    BLUETOOTH_SCAN,
    BLUETOOTH_CONNECT,
    BLUETOOTH_ADMIN,
    BLUETOOTH_ADVERTISE,
    ACCESS_COARSE_LOCATION,
    ACCESS_FINE_LOCATION,
    ACTION_REQUEST_ENABLE,
    ACTION_REQUEST_DISCOVERABLE
}